/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import Facade.Inicializador;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author Luis Rafael
 */
public class frmProyecto extends javax.swing.JFrame {
    private JPanel contenedor;
    private Inicializador inicio;
    public static final String MENU_PRINCIPAL = "menuPrincipal";
    public static final String MENU_ALUMNO = "menuAlumno";
    public static final String MENU_CURSOS = "menuCursos";
    public static final String MENU_REPORTES = "menuReportes";
    public static final String MENU_CALIFICACIONES = "menuCalificaciones";
    public static final String MENU_INSCRIPCIONES = "menuInscripciones";
    /**
     * 
     */
    public frmProyecto() {
        initComponents();
        setLayout(null);
        setResizable(false);
        
        inicio = new Inicializador();
        
        contenedor = new JPanel(new CardLayout());
        
        menuPrincipal mPrincipal = new menuPrincipal(this, inicio);
        menuEstudiantes mAlumnos = new menuEstudiantes(this, inicio);
        menuCursos mCursos = new menuCursos(this, inicio);
        menuReportes mReportes = new menuReportes(this, inicio);
        menuCalificaciones mCalificaciones = new menuCalificaciones(this, inicio);
        menuInscripciones mInscripciones = new menuInscripciones(this, inicio);
        
        contenedor.add(mPrincipal, MENU_PRINCIPAL);
        contenedor.add(mAlumnos, MENU_ALUMNO);
        contenedor.add(mCursos, MENU_CURSOS);
        contenedor.add(mReportes, MENU_REPORTES);
        contenedor.add(mCalificaciones, MENU_CALIFICACIONES);
        contenedor.add(mInscripciones, MENU_INSCRIPCIONES);
        
        add(contenedor); 
        setContentPane(contenedor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmProyecto().setVisible(true);
        });
    }
    
    
    public void cambiarPanel(String nombrePanel) {
        CardLayout cl = (CardLayout) contenedor.getLayout();
        cl.show(contenedor, nombrePanel);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
